event source selector fix (#573)
Tracardi/tracardi-gui pull request #187
Opened 2022-07-14 19:17 UTC by DawidekZagajnik

Pull Request title
-------------------

     event source selector fix (#573)

Pull Request description
-------------------------

    Pull request description

----

We need your declaration that your contribution is MIT licensed without it, we can not merge your code.
To make clear that you license your contribution under the MIT you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [MIT license](https://opensource.org/licenses/MIT)

2022-07-14 22:07 UTC, atompie requested changes

2022-07-14 22:07 UTC, atompie commented on src/components/elements/forms/ImportForm.js
> +                                                  onSetValue={(value) => {eventSource.current = value; console.log(eventSource.current);}}
Please remove console log

2022-07-15 17:51 UTC, DawidekZagajnik commented on src/components/elements/forms/ImportForm.js
> +                                                  onSetValue={(value) => {eventSource.current = value; console.log(eventSource.current);}}
done

2022-07-18 22:48 UTC, atompie approved these changes

2022-07-18 22:48 UTC, merged