icon-selector with material-ui and redux
Tracardi/tracardi-gui pull request #56
Opened 2021-11-19 14:02 UTC by PiotrKukuc12

I had to export icons object from FlowNodeIcons, I belive there is better way to make this work without duplicating

2021-11-20 11:15 UTC, atompie commented
@PiotrKukuc12 I was going to ask you about it. I will take a look at this and will get back to you￼

2021-11-20 22:42 UTC, atompie requested changes
Please add input field and make it act as described in the task. Thanks.

2021-11-20 22:42 UTC, atompie commented on src/components/elements/IconSelector.js
> +  return (
The component has not all the functionality described in the task. 

* There is no input field that the icon name should be copied. 
* Positioning of the popover is not the same as on the wire-frame

2021-11-20 22:42 UTC, atompie commented on src/components/flow/FlowNodeIcons.js
> +export const icons = {
Icons that exist in the FlowNodeIcons function  can be moved outside the function:

```
export const icons = {
        "store": <FiDatabase size={size}/>,
        "json": <VscJson size={size}/>,
        "split": <BiGitRepoForked size={size} style={{ transform: "rotateX(180deg)"}}/>,
        "join": <BiGitRepoForked size={size} />,
...
}

export default function FlowNodeIcons({icon, size=20}) {
....
```
This was the list can be exported and also used in the FlowNodeIcons. This solves the problem of duplicated icon list.

2021-11-20 22:42 UTC, atompie commented on src/redux/reducers/iconSlice.js
> +import { createSlice } from '@reduxjs/toolkit';
Why did you use redux for such a trival operation as adding icon. Icon as described in task should be copied to input field that is a part of this component. Then onChange property could be set to notify any outer component about the change. 

Using redux has its drawbacks. It always re-renders the whole application. Therefore it should be used with caution only for cross component actions.

2021-11-20 22:42 UTC, atompie commented on src/redux/store.js
> +            pagingReducer,
See comment above.

2021-11-22 21:19 UTC, PiotrKukuc12 commented
I have clearly misunderstood task. I thought it might be good idea to add an icon that saves the name to clipboard, let me know if it is a bad idea, then i'll remove it. Hope it now works as it should.

2021-11-23 21:14 UTC, merged